# Generated by Django 4.2.6 on 2024-03-14 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companieName', models.CharField(max_length=255)),
                ('companieTypeChategory', models.CharField(choices=[('M', 'MANUFUCTURING'), ('R', 'RETAIL')], max_length=1)),
                ('phone_name', models.CharField(max_length=255)),
                ('companieAdress', models.CharField(max_length=255)),
                ('chategory', models.CharField(blank=True, choices=[('EL', 'ELECTRONICS'), ('FB', 'FASHION & BEAUTY'), ('FO', 'FOOD & BEVERAGE'), ('CD', 'CONSOMOTICS & DETERGENT'), ('OT', 'OTHER')], max_length=2, null=True)),
                ('custom_category', models.CharField(blank=True, max_length=225, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
