# Generated by Django 4.2.6 on 2024-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='companiesOwnerName',
            field=models.CharField(default='user', max_length=225),
            preserve_default=False,
        ),
    ]
